manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dima3-zmk
      url-base: https://github.com/torshin
  projects:
    - name: zmk
      remote: dima3-zmk
      revision: dima3-module
      import: app/west.yml
  self:
    path: config
