manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/torshin/zmk-config/
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: dima3-module
      import: app/west.yml
  self:
    path: config
